[project]
name = "opera-ald8"
version = "1.0.0"
description = "Sistema operativo de almacén Opera Ald8"
requires-python = ">=3.12"

[tool.flet]
org = "com.operaald8"
product = "Opera Ald8"

[tool.flet.android]
package = "com.operaald8.app"
dependencies = [
    "flet",
    "requests",
    "pandas",
    "openpyxl"
    
]
[tool.flet.android.signing]
keystore = "lifealdea8.keystore"
keystore-password = "rreload"
key-alias = "lifealdea8"
key-password = "rreload"